In [1]:
import pandas as pd
import numpy as np
from google.colab import files

In [2]:
upload = files.upload()

Saving superstore_expanded.xlsx to superstore_expanded.xlsx

In [3]:
xls = pd.ExcelFile('superstore_expanded.xlsx')

# Print the names of all sheets in the workbook
print("Sheets in the Excel workbook:", xls.sheet_names)

Sheets in the Excel workbook: ['Orders', 'People', 'Returns']

In [4]:
df = pd.read_excel('superstore_expanded.xlsx',sheet_name = 'Orders')

In [5]:
df.shape

(75194, 21)

In [6]:
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
5,6,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078
6,7,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-AR-10001662,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.480,2,0.0,1.4796
7,8,US-2023-106054,2023-01-06,2023-01-07,First Class,JO-15145,Jack O'Briant,Corporate,United States,Athens,...,30605,South,OFF-AR-10002399,Office Supplies,Art,"Dixon Prang Watercolor Pencils, 10-Color Set w...",12.780,3,0.0,5.2398
8,9,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-BI-10004632,Office Supplies,Binders,Ibico Hi-Tech Manual Binding System,609.980,2,0.0,274.4910
9,10,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-FA-10001883,Office Supplies,Fasteners,"Alliance Super-Size Bands, Assorted Sizes",31.120,4,0.0,0.3112

In [7]:
df.tail(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
75184,75185,US-2023-708059,2023-10-08,2023-10-13,Second Class,LW-17215,Luke Weiss,Consumer,United States,Buffalo,...,14215,East,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,404.7433,2,0.7,180.7151
75185,75186,US-2026-796320,2026-07-08,2026-07-12,Second Class,EH-14005,Erica Hernandez,Home Office,United States,Wichita,...,67212,Central,OFF-LA-10004008,Office Supplies,Labels,Avery 507,26.3482,4,0.0,13.4719
75186,75187,US-2024-789901,2024-02-25,2024-03-02,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Miami,...,33178,South,TEC-MA-10004458,Technology,Machines,Lexmark X 9575 Professional All-in-One Color P...,572.9028,2,0.1,47.2481
75187,75188,US-2024-339843,2024-12-26,2024-12-28,First Class,RM-19750,Roland Murray,Consumer,United States,Orlando,...,32839,South,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,207.8742,4,0.0,18.1307
75188,75189,US-2023-846568,2023-02-10,2023-02-14,Standard Class,FW-14395,Fred Wasserman,Corporate,United States,Dearborn Heights,...,48127,Central,OFF-PA-10004782,Office Supplies,Paper,Xerox 228,27.8933,2,0.0,15.2596
75189,75190,CA-2024-861319,2024-02-03,2024-02-03,Same Day,AM-10705,Anne McFarland,Consumer,Canada,Vancouver,...,V6B,West,OFF-FA-10000089,Office Supplies,Fasteners,Acco Glide Clips,3.6391,7,0.0,1.5685
75190,75191,US-2026-367865,2026-03-15,2026-03-18,First Class,KC-16255,Karen Carlisle,Corporate,United States,Lewiston,...,4240,East,OFF-AR-10001166,Office Supplies,Art,Staples in misc. colors,27.5442,2,0.0,10.0847
75191,75192,US-2025-284308,2025-09-23,2025-09-28,Standard Class,KD-16345,Katherine Ducich,Consumer,United States,Laurel,...,20707,East,OFF-FA-10002280,Office Supplies,Fasteners,Advantus Plastic Paper Clips,4.0983,1,0.2,1.4678
75192,75193,US-2023-315815,2023-11-01,2023-11-05,Standard Class,MA-17560,Matt Abelman,Home Office,United States,Los Angeles,...,90049,West,OFF-FA-10002763,Office Supplies,Fasteners,Advantus Map Pennant Flags and Round Head Tacks,4.5573,13,0.0,1.2680
75193,75194,US-2024-740939,2024-01-26,2024-02-01,Standard Class,JF-15355,Jay Fein,Consumer,United States,Mishawaka,...,46544,Central,OFF-AR-10004027,Office Supplies,Art,Binney & Smith inkTank Erasable Desk Highlight...,8.9883,7,0.0,0.9334

In [8]:
df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country/Region            object
City                      object
State/Province            object
Postal Code               object
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
dtype: object

In [9]:
df.isnull().sum()

Row ID               0
Order ID             0
Order Date           0
Ship Date            0
Ship Mode            0
Customer ID          0
Customer Name        0
Segment              0
Country/Region       0
City                 0
State/Province       0
Postal Code       1291
Region               0
Product ID           0
Category             0
Sub-Category         0
Product Name         0
Sales                0
Quantity             0
Discount             0
Profit               0
dtype: int64

# Data Cleaning

In [10]:
# Drop Row Id Column
df = df.drop('Row ID', axis=1)
display(df.head())

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [11]:
# Replace any null values in postal code column to "N/A"

df['Postal Code'] = df['Postal Code'].fillna('N/A')
print(f"Null values in 'Postal Code' after filling: {df['Postal Code'].isnull().sum()}")

Null values in 'Postal Code' after filling: 0

In [12]:
# Check to see if any rows in the sales or quantinty columns have negative values
print(f"Negative values in 'Sales' column: {df[df['Sales'] < 0].shape[0]}")
print(f"Negative values in 'Quantity' column: {df[df['Quantity'] < 0].shape[0]}")

Negative values in 'Sales' column: 0
Negative values in 'Quantity' column: 147

In [13]:
# Show some of the rows that have negative quantity values
df[df['Quantity'] < 0].head(10)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
51,US-2023-167927,2023-01-20,2023-01-26,Standard Class,XP-21865,Xylona Preis,Consumer,United States,Westland,Michigan,48185,Central,OFF-AR-10004456,Office Supplies,Art,Panasonic KP-4ABK Battery-Operated Pencil Shar...,43.920,-3,0.0,12.7368
514,CA-2023-152443,2023-05-21,2023-05-26,Standard Class,FG-14260,Frank Gastineau,Home Office,Canada,Montreal,Quebec,H1A,East,OFF-AP-10001293,Office Supplies,Appliances,Belkin 8 Outlet Surge Protector,245.880,-6,0.0,68.8464
575,US-2023-163867,2023-06-03,2023-06-06,First Class,RE-19450,Richard Eichhorn,Consumer,United States,Decatur,Illinois,62521,Central,OFF-LA-10001771,Office Supplies,Labels,Avery 513,15.936,-4,0.2,5.1792
783,US-2023-116932,2023-07-21,2023-07-25,Standard Class,ME-18010,Michelle Ellison,Corporate,United States,San Francisco,California,94122,West,FUR-CH-10001215,Furniture,Chairs,Global Troy Executive Leather Low-Back Tilter,801.568,-2,0.2,50.0980
1000,US-2023-138828,2023-09-02,2023-09-03,First Class,KD-16345,Katherine Ducich,Consumer,United States,New York City,New York,10009,East,OFF-AR-10000658,Office Supplies,Art,Newell 324,57.750,-5,0.0,16.1700
1116,US-2023-160766,2023-09-14,2023-09-14,Same Day,DM-13015,Darrin Martin,Consumer,United States,New York City,New York,10009,East,OFF-AP-10002945,Office Supplies,Appliances,Honeywell Enviracaire Portable HEPA Air Cleane...,601.300,-2,0.0,198.4290
1232,US-2023-115049,2023-09-26,2023-10-01,Standard Class,MM-17920,Michael Moore,Consumer,United States,Chicago,Illinois,60623,Central,TEC-AC-10004859,Technology,Accessories,"Maxell Pro 80 Minute CD-R, 10/Pack",153.824,-11,0.2,38.4560
1541,US-2023-140914,2023-11-11,2023-11-15,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Chicago,Illinois,60653,Central,FUR-FU-10000175,Furniture,Furnishings,DAX Wood Document Frame,10.984,-2,0.6,-7.9634
1730,US-2023-167486,2023-11-27,2023-12-01,Standard Class,JO-15145,Jack O'Briant,Corporate,United States,Buffalo,New York,14215,East,FUR-FU-10003268,Furniture,Furnishings,Eldon Radial Chair Mat for Low to Medium Pile ...,199.900,-5,0.0,39.9800
2119,US-2024-103093,2024-02-03,2024-02-07,Standard Class,FO-14305,Frank Olsen,Consumer,United States,Columbus,Georgia,31907,South,OFF-EN-10003286,Office Supplies,Envelopes,Staple envelope,74.520,-9,0.0,35.0244

In [14]:
# Drop rows where 'Quantity' is negative
df = df[df['Quantity'] >= 0]
print(f"Shape of DataFrame after dropping rows with negative Quantity: {df.shape}")

Shape of DataFrame after dropping rows with negative Quantity: (75047, 20)

In [15]:
# Check for duplicate rows
duplicate_rows = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_rows}")

df = df.drop_duplicates()
print(f"Shape of DataFrame after dropping duplicates: {df.shape}")

Number of duplicate rows: 194
Shape of DataFrame after dropping duplicates: (74853, 20)

## Inspecting Categorical Columns

In [16]:
# Identify categorical columns
categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    print(f"\n--- Column: {col} ---")
    print(f"Number of unique values: {df[col].nunique()}")
    display(df[col].value_counts())

--- Column: Order ID ---
Number of unique values: 37459

Order ID
US-2026-682052    14
US-2024-765620    14
US-2023-932378    14
US-2026-100111    14
US-2026-223179    14
                  ..
US-2025-703637     1
US-2026-227780     1
US-2023-806042     1
US-2023-103366     1
US-2023-149524     1
Name: count, Length: 37459, dtype: int64

--- Column: Ship Mode ---
Number of unique values: 8

Ship Mode
Standard Class     44628
Second Class       14366
First Class        11274
Same Day            3968
Standard  Class      391
2nd Class            114
First class           82
Same-Day              30
Name: count, dtype: int64

--- Column: Customer ID ---
Number of unique values: 804

Customer ID
SP-20860    153
Dp-13240    142
NM-18520    136
JD-16015    133
BH-11710    133
           ...
ES-14020     55
NC-19470     55
BF-11215     49
TB-21190     45
EJ-14155     44
Name: count, Length: 804, dtype: int64

--- Column: Customer Name ---
Number of unique values: 1502

Customer Name
Harry Olson             365
Sung Pak                151
Dean percer             142
Neoma Murray            135
Brosina Hoffman         133
                       ...
vivek grady               1
  DIANNA WILSON           1
  VALERIE TAKAHITO        1
  BART FOLK               1
  SCOTT WILLIAMSON        1
Name: count, Length: 1502, dtype: int64

--- Column: Segment ---
Number of unique values: 3

Segment
Consumer       38941
Corporate      22267
Home Office    13645
Name: count, dtype: int64

--- Column: Country/Region ---
Number of unique values: 2

Country/Region
United States    72367
Canada            2486
Name: count, dtype: int64

--- Column: City ---
Number of unique values: 890

City
New York City    1302
Los Angeles      1261
Philadelphia      890
San Francisco     814
Houston           766
                 ...
WESTLAND            1
QUINCY              1
VINELAND            1
OLYMPIA             1
BRENTWOOD           1
Name: count, Length: 890, dtype: int64

--- Column: State/Province ---
Number of unique values: 67

State/Province
California    10611
Texas          6849
Illinois       4179
Florida        4075
New York       3112
              ...
OH               12
FL               12
NY               10
WA               10
PA                3
Name: count, Length: 67, dtype: int64

--- Column: Postal Code ---
Number of unique values: 655

Postal Code
N/A      1286
10035     350
10024     344
10009     335
94122     287
         ...
80122      62
37075      62
82001      62
59102      58
79605      53
Name: count, Length: 655, dtype: int64

--- Column: Region ---
Number of unique values: 4

Region
Central    21835
West       21721
East       16079
South      15218
Name: count, dtype: int64

--- Column: Product ID ---
Number of unique values: 1862

Product ID
TEC-CO-10001449    333
TEC-CO-10002313    324
TEC-CO-10001766    318
TEC-CO-10004115    309
TEC-CO-10004722    304
                  ...
OFF-PA-10001274     10
OFF-PA-10004733     10
OFF-PA-10004470     10
OFF-PA-10002764      9
OFF-PA-10000048      9
Name: count, Length: 1862, dtype: int64

--- Column: Category ---
Number of unique values: 3

Category
Office Supplies    40283
Furniture          17343
Technology         17227
Name: count, dtype: int64

--- Column: Sub-Category ---
Number of unique values: 17

Sub-Category
Binders        5290
Paper          5211
Furnishings    4803
Phones         4802
Storage        4694
Accessories    4633
Art            4516
Chairs         4429
Appliances     4318
Labels         4152
Envelopes      4143
Tables         4092
Fasteners      4040
Bookcases      4019
Supplies       3919
Machines       3904
Copiers        3888
Name: count, dtype: int64

--- Column: Product Name ---
Number of unique values: 1849

Product Name
Staples                                                                917
Staple envelope                                                        671
Hewlett Packard LaserJet 3310 Copier                                   333
Canon PC1080F Personal Copier                                          324
Canon PC940 Copier                                                     318
                                                                      ...
Loose Memo Sheets                                                       10
Things To Do Today Spiral Book                                          10
Adams Write n' Stick Phone Message Book, 11" X 5 1/4", 200 Messages     10
Geographics Note Cards, Blank, White, 8 1/2" x 11"                      10
Xerox 20                                                                 9
Name: count, Length: 1849, dtype: int64

### Cleaning 'Ship Mode' Column

In [17]:
# Standardize 'Ship Mode' values
ship_mode_mapping = {
    'Standard  Class': 'Standard Class',
    '2nd Class': 'Second Class',
    'First class': 'First Class',
    'Same-Day': 'Same Day'
}

df['Ship Mode'] = df['Ship Mode'].replace(ship_mode_mapping)

print("Value counts for 'Ship Mode' after standardization:")
display(df['Ship Mode'].value_counts())

Value counts for 'Ship Mode' after standardization:

Ship Mode
Standard Class    45019
Second Class      14480
First Class       11356
Same Day           3998
Name: count, dtype: int64

### Continuing Inspection of Categorical Columns

In [18]:
# List of columns already inspected (or cleaned):
inspected_cols = ['Order ID', 'Ship Mode', 'Customer ID']

# Identify remaining categorical columns to inspect
all_categorical_cols = df.select_dtypes(include='object').columns
remaining_categorical_cols = [col for col in all_categorical_cols if col not in inspected_cols]

print("Inspecting remaining categorical columns:")
for col in remaining_categorical_cols:
    print(f"\n--- Column: {col} ---")
    print(f"Number of unique values: {df[col].nunique()}")
    display(df[col].value_counts())

Inspecting remaining categorical columns:

--- Column: Customer Name ---
Number of unique values: 1502

Customer Name
Harry Olson             365
Sung Pak                151
Dean percer             142
Neoma Murray            135
Brosina Hoffman         133
                       ...
vivek grady               1
  DIANNA WILSON           1
  VALERIE TAKAHITO        1
  BART FOLK               1
  SCOTT WILLIAMSON        1
Name: count, Length: 1502, dtype: int64

--- Column: Segment ---
Number of unique values: 3

Segment
Consumer       38941
Corporate      22267
Home Office    13645
Name: count, dtype: int64

--- Column: Country/Region ---
Number of unique values: 2

Country/Region
United States    72367
Canada            2486
Name: count, dtype: int64

--- Column: City ---
Number of unique values: 890

City
New York City    1302
Los Angeles      1261
Philadelphia      890
San Francisco     814
Houston           766
                 ...
WESTLAND            1
QUINCY              1
VINELAND            1
OLYMPIA             1
BRENTWOOD           1
Name: count, Length: 890, dtype: int64

--- Column: State/Province ---
Number of unique values: 67

State/Province
California    10611
Texas          6849
Illinois       4179
Florida        4075
New York       3112
              ...
OH               12
FL               12
NY               10
WA               10
PA                3
Name: count, Length: 67, dtype: int64

--- Column: Postal Code ---
Number of unique values: 655

Postal Code
N/A      1286
10035     350
10024     344
10009     335
94122     287
         ...
80122      62
37075      62
82001      62
59102      58
79605      53
Name: count, Length: 655, dtype: int64

--- Column: Region ---
Number of unique values: 4

Region
Central    21835
West       21721
East       16079
South      15218
Name: count, dtype: int64

--- Column: Product ID ---
Number of unique values: 1862

Product ID
TEC-CO-10001449    333
TEC-CO-10002313    324
TEC-CO-10001766    318
TEC-CO-10004115    309
TEC-CO-10004722    304
                  ...
OFF-PA-10001274     10
OFF-PA-10004733     10
OFF-PA-10004470     10
OFF-PA-10002764      9
OFF-PA-10000048      9
Name: count, Length: 1862, dtype: int64

--- Column: Category ---
Number of unique values: 3

Category
Office Supplies    40283
Furniture          17343
Technology         17227
Name: count, dtype: int64

--- Column: Sub-Category ---
Number of unique values: 17

Sub-Category
Binders        5290
Paper          5211
Furnishings    4803
Phones         4802
Storage        4694
Accessories    4633
Art            4516
Chairs         4429
Appliances     4318
Labels         4152
Envelopes      4143
Tables         4092
Fasteners      4040
Bookcases      4019
Supplies       3919
Machines       3904
Copiers        3888
Name: count, dtype: int64

--- Column: Product Name ---
Number of unique values: 1849

Product Name
Staples                                                                917
Staple envelope                                                        671
Hewlett Packard LaserJet 3310 Copier                                   333
Canon PC1080F Personal Copier                                          324
Canon PC940 Copier                                                     318
                                                                      ...
Loose Memo Sheets                                                       10
Things To Do Today Spiral Book                                          10
Adams Write n' Stick Phone Message Book, 11" X 5 1/4", 200 Messages     10
Geographics Note Cards, Blank, White, 8 1/2" x 11"                      10
Xerox 20                                                                 9
Name: count, Length: 1849, dtype: int64

### Cleaning 'Customer Name' Column

In [19]:
# Standardize 'Customer Name' by converting to title case and stripping whitespace
df['Customer Name'] = df['Customer Name'].str.strip().str.title()

print("Value counts for 'Customer Name' after standardization:")
display(df['Customer Name'].value_counts())

Value counts for 'Customer Name' after standardization:

Customer Name
Harry Olson        375
Sung Pak           153
Dean Percer        142
Neoma Murray       136
Laura Armstrong    133
                  ...
Neil Cohen          55
Erica Smith         55
Benjamin Farhat     49
Thomas Brumley      45
Eva Jacobs          44
Name: count, Length: 800, dtype: int64

### Continued Inspection of Remaining Categorical Columns

In [20]:
# Update the list of columns already cleaned):
inspected_cols = ['Order ID', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment']

# Identify remaining categorical columns to inspect
all_categorical_cols = df.select_dtypes(include='object').columns
remaining_categorical_cols = [col for col in all_categorical_cols if col not in inspected_cols]

print("Inspecting remaining categorical columns:")
for col in remaining_categorical_cols:
    print(f"\n--- Column: {col} ---")
    print(f"Number of unique values: {df[col].nunique()}")
    display(df[col].value_counts())

Inspecting remaining categorical columns:

--- Column: Country/Region ---
Number of unique values: 2

Country/Region
United States    72367
Canada            2486
Name: count, dtype: int64

--- Column: City ---
Number of unique values: 890

City
New York City    1302
Los Angeles      1261
Philadelphia      890
San Francisco     814
Houston           766
                 ...
WESTLAND            1
QUINCY              1
VINELAND            1
OLYMPIA             1
BRENTWOOD           1
Name: count, Length: 890, dtype: int64

--- Column: State/Province ---
Number of unique values: 67

State/Province
California    10611
Texas          6849
Illinois       4179
Florida        4075
New York       3112
              ...
OH               12
FL               12
NY               10
WA               10
PA                3
Name: count, Length: 67, dtype: int64

--- Column: Postal Code ---
Number of unique values: 655

Postal Code
N/A      1286
10035     350
10024     344
10009     335
94122     287
         ...
80122      62
37075      62
82001      62
59102      58
79605      53
Name: count, Length: 655, dtype: int64

--- Column: Region ---
Number of unique values: 4

Region
Central    21835
West       21721
East       16079
South      15218
Name: count, dtype: int64

--- Column: Product ID ---
Number of unique values: 1862

Product ID
TEC-CO-10001449    333
TEC-CO-10002313    324
TEC-CO-10001766    318
TEC-CO-10004115    309
TEC-CO-10004722    304
                  ...
OFF-PA-10001274     10
OFF-PA-10004733     10
OFF-PA-10004470     10
OFF-PA-10002764      9
OFF-PA-10000048      9
Name: count, Length: 1862, dtype: int64

--- Column: Category ---
Number of unique values: 3

Category
Office Supplies    40283
Furniture          17343
Technology         17227
Name: count, dtype: int64

--- Column: Sub-Category ---
Number of unique values: 17

Sub-Category
Binders        5290
Paper          5211
Furnishings    4803
Phones         4802
Storage        4694
Accessories    4633
Art            4516
Chairs         4429
Appliances     4318
Labels         4152
Envelopes      4143
Tables         4092
Fasteners      4040
Bookcases      4019
Supplies       3919
Machines       3904
Copiers        3888
Name: count, dtype: int64

--- Column: Product Name ---
Number of unique values: 1849

Product Name
Staples                                                                917
Staple envelope                                                        671
Hewlett Packard LaserJet 3310 Copier                                   333
Canon PC1080F Personal Copier                                          324
Canon PC940 Copier                                                     318
                                                                      ...
Loose Memo Sheets                                                       10
Things To Do Today Spiral Book                                          10
Adams Write n' Stick Phone Message Book, 11" X 5 1/4", 200 Messages     10
Geographics Note Cards, Blank, White, 8 1/2" x 11"                      10
Xerox 20                                                                 9
Name: count, Length: 1849, dtype: int64

### Cleaning 'City' and 'State/Province' Columns

In [21]:
# Standardize 'City' and 'State/Province' by converting to title case and stripping whitespace
df['City'] = df['City'].str.strip().str.title()
df['State/Province'] = df['State/Province'].str.strip().str.title()

print("Value counts for 'City' after standardization (top 10):")
display(df['City'].value_counts().head(10))

print("\nValue counts for 'State/Province' after standardization (top 10):")
display(df['State/Province'].value_counts().head(10))

Value counts for 'City' after standardization (top 10):

City
New York City    1310
Los Angeles      1270
Philadelphia      892
San Francisco     819
Houston           769
Seattle           707
Chicago           656
Vancouver         650
Springfield       584
Columbus          518
Name: count, dtype: int64

Value counts for 'State/Province' after standardization (top 10):

State/Province
California        10611
Texas              6849
Illinois           4179
Florida            4075
New York           3112
Ohio               2823
Washington         2530
Michigan           2454
North Carolina     2124
New Jersey         1981
Name: count, dtype: int64

### Continuing Inspection of Remaining Categorical Columns

In [22]:
# Update the list of columns already inspected (or cleaned):
inspected_cols = ['Order ID', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City', 'State/Province']

# Identify remaining categorical columns to inspect
all_categorical_cols = df.select_dtypes(include='object').columns
remaining_categorical_cols = [col for col in all_categorical_cols if col not in inspected_cols]

print("Inspecting remaining categorical columns:")
for col in remaining_categorical_cols:
    print(f"\n--- Column: {col} ---")
    print(f"Number of unique values: {df[col].nunique()}")
    display(df[col].value_counts())

Inspecting remaining categorical columns:

--- Column: Postal Code ---
Number of unique values: 655

Postal Code
N/A      1286
10035     350
10024     344
10009     335
94122     287
         ...
80122      62
37075      62
82001      62
59102      58
79605      53
Name: count, Length: 655, dtype: int64

--- Column: Region ---
Number of unique values: 4

Region
Central    21835
West       21721
East       16079
South      15218
Name: count, dtype: int64

--- Column: Product ID ---
Number of unique values: 1862

Product ID
TEC-CO-10001449    333
TEC-CO-10002313    324
TEC-CO-10001766    318
TEC-CO-10004115    309
TEC-CO-10004722    304
                  ...
OFF-PA-10001274     10
OFF-PA-10004733     10
OFF-PA-10004470     10
OFF-PA-10002764      9
OFF-PA-10000048      9
Name: count, Length: 1862, dtype: int64

--- Column: Category ---
Number of unique values: 3

Category
Office Supplies    40283
Furniture          17343
Technology         17227
Name: count, dtype: int64

--- Column: Sub-Category ---
Number of unique values: 17

Sub-Category
Binders        5290
Paper          5211
Furnishings    4803
Phones         4802
Storage        4694
Accessories    4633
Art            4516
Chairs         4429
Appliances     4318
Labels         4152
Envelopes      4143
Tables         4092
Fasteners      4040
Bookcases      4019
Supplies       3919
Machines       3904
Copiers        3888
Name: count, dtype: int64

--- Column: Product Name ---
Number of unique values: 1849

Product Name
Staples                                                                917
Staple envelope                                                        671
Hewlett Packard LaserJet 3310 Copier                                   333
Canon PC1080F Personal Copier                                          324
Canon PC940 Copier                                                     318
                                                                      ...
Loose Memo Sheets                                                       10
Things To Do Today Spiral Book                                          10
Adams Write n' Stick Phone Message Book, 11" X 5 1/4", 200 Messages     10
Geographics Note Cards, Blank, White, 8 1/2" x 11"                      10
Xerox 20                                                                 9
Name: count, Length: 1849, dtype: int64

### Final Inspection of Remaining Categorical Columns

In [23]:
# Update the list of columns already inspected (or cleaned):
inspected_cols = ['Order ID', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Region', 'Product ID']

# Identify remaining categorical columns to inspect
all_categorical_cols = df.select_dtypes(include='object').columns
remaining_categorical_cols = [col for col in all_categorical_cols if col not in inspected_cols]

print("Inspecting remaining categorical columns:")
for col in remaining_categorical_cols:
    print(f"\n--- Column: {col} ---")
    print(f"Number of unique values: {df[col].nunique()}")
    display(df[col].value_counts())

Inspecting remaining categorical columns:

--- Column: Category ---
Number of unique values: 3

Category
Office Supplies    40283
Furniture          17343
Technology         17227
Name: count, dtype: int64

--- Column: Sub-Category ---
Number of unique values: 17

Sub-Category
Binders        5290
Paper          5211
Furnishings    4803
Phones         4802
Storage        4694
Accessories    4633
Art            4516
Chairs         4429
Appliances     4318
Labels         4152
Envelopes      4143
Tables         4092
Fasteners      4040
Bookcases      4019
Supplies       3919
Machines       3904
Copiers        3888
Name: count, dtype: int64

--- Column: Product Name ---
Number of unique values: 1849

Product Name
Staples                                                                917
Staple envelope                                                        671
Hewlett Packard LaserJet 3310 Copier                                   333
Canon PC1080F Personal Copier                                          324
Canon PC940 Copier                                                     318
                                                                      ...
Loose Memo Sheets                                                       10
Things To Do Today Spiral Book                                          10
Adams Write n' Stick Phone Message Book, 11" X 5 1/4", 200 Messages     10
Geographics Note Cards, Blank, White, 8 1/2" x 11"                      10
Xerox 20                                                                 9
Name: count, Length: 1849, dtype: int64

## Inspecting Numerical Columns

In [24]:
# Identify numerical columns
numerical_cols = df.select_dtypes(include=np.number).columns

print("Inspecting numerical columns:")
for col in numerical_cols:
    print(f"\n--- Column: {col} ---")
    display(df[col].describe())

Inspecting numerical columns:

--- Column: Sales ---

count    74853.000000
mean       395.116797
std       1154.133501
min          0.444000
25%         19.074700
50%         73.916200
75%        335.124900
max      29400.448600
Name: Sales, dtype: float64

--- Column: Quantity ---

count    74853.000000
mean         3.778806
std          2.207290
min          1.000000
25%          2.000000
50%          3.000000
75%          5.000000
max         14.000000
Name: Quantity, dtype: float64

--- Column: Discount ---

count    74853.000000
mean         0.170013
std          0.927802
min          0.000000
25%          0.000000
50%          0.200000
75%          0.200000
max         80.000000
Name: Discount, dtype: float64

--- Column: Profit ---

count    74853.000000
mean        34.196310
std        540.878218
min     -49743.365600
25%          1.236200
50%          8.047100
75%         36.711600
max      14955.996600
Name: Profit, dtype: float64

In [25]:
# Continue inspecting remaining numerical columns if any were truncated
numerical_cols_remaining = ['Discount', 'Profit']

print("Continuing inspection of numerical columns:")
for col in numerical_cols_remaining:
    print(f"\n--- Column: {col} ---")
    display(df[col].describe())

Continuing inspection of numerical columns:

--- Column: Discount ---

count    74853.000000
mean         0.170013
std          0.927802
min          0.000000
25%          0.000000
50%          0.200000
75%          0.200000
max         80.000000
Name: Discount, dtype: float64

--- Column: Profit ---

count    74853.000000
mean        34.196310
std        540.878218
min     -49743.365600
25%          1.236200
50%          8.047100
75%         36.711600
max      14955.996600
Name: Profit, dtype: float64

In [26]:
df.head(10)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
5,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,Kentucky,42420,South,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078
6,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,Kentucky,42420,South,OFF-AR-10001662,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.480,2,0.0,1.4796
7,US-2023-106054,2023-01-06,2023-01-07,First Class,JO-15145,Jack O'Briant,Corporate,United States,Athens,Georgia,30605,South,OFF-AR-10002399,Office Supplies,Art,"Dixon Prang Watercolor Pencils, 10-Color Set w...",12.780,3,0.0,5.2398
8,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,Kentucky,42420,South,OFF-BI-10004632,Office Supplies,Binders,Ibico Hi-Tech Manual Binding System,609.980,2,0.0,274.4910
9,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,Kentucky,42420,South,OFF-FA-10001883,Office Supplies,Fasteners,"Alliance Super-Size Bands, Assorted Sizes",31.120,4,0.0,0.3112

In [27]:
df.tail(10)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
74992,US-2025-658511,2025-11-13,2025-11-16,First Class,JK-15325,Jason Klamczynski,Corporate,United States,Rapid City,South Dakota,57701,Central,OFF-AR-10004260,Office Supplies,Art,Boston 1799 Powerhouse Electric Pencil Sharpener,53.4978,3,0.2,15.1990
74993,US-2024-231753,2024-12-30,2025-01-03,Standard Class,PJ-18835,Patrick Jones,Corporate,United States,Aurora,Illinois,N/A,Central,FUR-TA-10003954,Furniture,Tables,Hon 94000 Series Round Tables,588.6300,2,0.5,28.0613
74994,US-2026-994258,2026-11-06,2026-11-13,Standard Class,DB-13270,Deborah Brumfield,Home Office,United States,Lawrence,Indiana,46226,Central,OFF-ST-10000046,Office Supplies,Storage,Fellowes Super Stor/Drawer Files,56.5208,2,0.0,18.0052
74995,US-2026-994258,2026-11-06,2026-11-13,Standard Class,DB-13270,Deborah Brumfield,Home Office,United States,Lawrence,Indiana,46226,Central,FUR-BO-10004357,Furniture,Bookcases,O'Sullivan Living Dimensions 3-Shelf Bookcases,100.5890,5,0.2,3.0429
74996,US-2025-701363,2025-05-02,2025-05-07,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Columbia,Tennessee,38401,South,FUR-FU-10002030,Furniture,Furnishings,"Executive Impressions 14"" Contract Wall Clock ...",37.1378,2,0.0,9.9891
74997,US-2025-701363,2025-05-02,2025-05-07,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Columbia,Tennessee,38401,South,OFF-BI-10001989,Office Supplies,Binders,Premium Transparent Presentation Covers by GBC,4.3039,2,0.7,-6.6954
74998,US-2025-701363,2025-05-02,2025-05-07,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Columbia,Tennessee,38401,South,TEC-CO-10003236,Technology,Copiers,Canon Image Class D660 Copier,618.7639,3,0.2,230.5326
74999,US-2025-701363,2025-05-02,2025-05-07,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Columbia,Tennessee,38401,South,OFF-SU-10001165,Office Supplies,Supplies,Acme Elite Stainless Steel Scissors,9.5717,7,0.0,-1.6565
75016,US-2023-721427,2023-09-24,2023-09-28,Standard Class,MK-18160,Mike Kennedy,Consumer,United States,San Bernardino,California,92404,West,OFF-PA-10000223,Office Supplies,Paper,Xerox 2000,17.9261,10,0.0,7.5633
75110,US-2026-187197,2026-04-17,2026-04-23,Standard Class,CT-11995,Carol Triggs,Consumer,United States,Englewood,Colorado,80112,West,FUR-FU-10003489,Furniture,Furnishings,Contemporary Borderless Frame,45.2840,2,60.0,19.5197

# Cleaning the "People" excel sheet

In [28]:
df2 = pd.read_excel('superstore_expanded.xlsx',sheet_name = 'People')
df2.head(10)

    Regional Manager   Region
0    Sadie Pawthorne     West
1        Chuck Magee     East
2  Roxanne Rodriguez  Central
3        Fred Suzuki    South

# Cleaning the "Returns" excel sheet

In [29]:
df3 = pd.read_excel('superstore_expanded.xlsx',sheet_name = 'Returns')
df3.head(10)

         Order ID Returned
0  US-2023-100762      Yes
1  US-2023-100867      Yes
2  US-2023-102652      Yes
3  US-2023-103373      Yes
4  US-2023-103744      Yes
5  US-2023-103940      Yes
6  US-2023-104829      Yes
7  US-2023-105270      Yes
8  US-2023-108609      Yes
9  US-2023-108861      Yes

In [30]:
# Check for duplicates in df3
duplicate_count = df3.duplicated().sum()
print(f"Number of duplicate rows in df3: {duplicate_count}")

if duplicate_count > 0:
    df3 = df3.drop_duplicates()
    print(f"Duplicates removed. New shape: {df3.shape}")

# Convert 'Returned' column to boolean
# 'Yes' becomes True, anything else (like NaN or No) becomes False
df3['Returned'] = df3['Returned'].apply(lambda x: True if str(x).strip().lower() == 'yes' else False)

print("\n'Returned' column converted to boolean.")
display(df3.head())
display(df3.dtypes)

Number of duplicate rows in df3: 0

'Returned' column converted to boolean.

         Order ID  Returned
0  US-2023-100762      True
1  US-2023-100867      True
2  US-2023-102652      True
3  US-2023-103373      True
4  US-2023-103744      True

Order ID    object
Returned      bool
dtype: object